name = "WBA Optimized"
author = "wiyba"
version = "1.21.8-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "404ad9958b06c22d155d0b2782d5da85578b8017c101d3db808939591d232a72"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.8"]
